# ------------------------------------ Node ------------------------------------
# Имя узла
node.name: es-nlb01

# Указываем роль Coordinating only
node.master: false
node.data: false
node.ingest: false
#
# ---------------------------------- Cluster -----------------------------------
#
cluster.name: es_cluster  # Имя кластера
#
# --------------------------------- Discovery ----------------------------------
discovery.seed_providers: file                       
#
# ---------------------------------- Network -----------------------------------
#
network.host: 10.0.3.2	          # Адрес узла
http.port: 9200					          # Порт
transport.host: 10.0.3.2          # Адрес для связи с кластером
transport.tcp.port: 9300-9400     # Порты для коммуникации внутри кластера
#
# ----------------------------------- Paths ------------------------------------
#
path.data: /var/lib/elasticsearch # Директория с данными
path.logs: /var/log/elasticsearch # Директория с логами
