# Адрес и порт
server.host: 10.0.3.2
server.port: 5601

# Узлы кластера Elasticsearch
elasticsearch.hosts:
  - http://10.0.3.11:9200
  - http://10.0.3.12:9200
  - http://10.0.3.13:9200

# Частота запросов обновления узлов кластера
# Запрос обновлений в случае сбоя подключения
elasticsearch.sniffInterval: 60000
elasticsearch.sniffOnConnectionFault: true

# Логи Kibana
logging.dest: /var/log/kibana/kibana.log
