---
- name: Deploy ELK

#Install and configure elasticsearch

  hosts: elasticsearch 
  become: yes
  
  vars:
    dest_repo_file: /etc/yum.repos.d/
    dest_cfg_file: /etc/elasticsearch/elasticsearch.yml

  tasks:

    - name: Add rpm key
      shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: Add repo in yum.repos.d
      vars:
        repo_file: elasticsearch.repo
      copy: 
        src: "{{ repo_file }}"
        dest: "{{ dest_repo_file }}"
    
    - name: Install elastic
      shell: yum install -y elasticsearch

    - name: Copy config
      vars:
        cfg_file: elasticsearch-01.yml
      copy:
        src: "{{ cfg_file }}"
        dest: "{{ dest_cfg_file }}"
      when: ansible_hostname == "es-node01"

    - name: Copy config
      vars:
        cfg_file: elasticsearch-02.yml
      copy:
        src: "{{ cfg_file }}"
        dest: "{{ dest_cfg_file }}"
      when: ansible_hostname == "es-node02"

    - name: Copy config
      vars:
        cfg_file: elasticsearch-03.yml
      copy:
        src: "{{ cfg_file }}"
        dest: "{{ dest_cfg_file }}"
      when: ansible_hostname == "es-node03"

    - name: Start elasticsearch
      service:
        name: elasticsearch
        state: started
        enabled: yes

#    - name: Heap size
#      shell: echo '-Xms16g' >> /etc/elasticsearch/jvm.options; echo '-Xmx16g' >> /etc/elasticsearch/jvm.options

    - name: Disable swapoff
      shell: swapoff -a

    - name: Edit sysctl
      shell: echo "vm.swappiness=1" >> sysctl.conf; sysctl -p

    - name: Restart elasticsearch
      service:
        name: elasticsearch
        state: restarted
        enabled: yes

#Install and configure kibana

  hosts: kibana
  become: yes
  
  vars: 
    dest_repo_file: /etc/yum.repos.d/
    dest_cfg_dir: /etc/kibana/
    dest_cfg_file: /etc/elasticsearch/elasticsearch.yml
    dest_cfg_dir_elastic: /etc/elasticsearch/

  tasks:

    - name: Add rpm key
      shell: sudo rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: Add repo in /etc/yum.repos.d/
      vars:
        repo_file: kibana.repo
      copy:
        src: "{{ repo_file }}"
        dest: "{{ dest_repo_file }}"

    - name: Install kibana
      shell: yum install -y kibana

    - name: Started kibana
      service:
        name: kibana
        state: started
        enabled: yes

    - name: Copy config file
      vars:
        cfg_file: kibana.yml
      copy:
        src: "{{ cfg_file }}"
        dest: "{{ dest_cfg_dir }}"

    - name: Copy config node.options
      shell: echo "--max-old-space-size=1024" > /etc/kibana/node.options

    - name: Restart kibana
      service:
        name: kibana
        state: restarted
        enabled: yes

    - name: Add rpm key
      shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: Add repo in yum.repos.d
      vars:
        repo_file: elasticsearch.repo
      copy: 
        src: "{{ repo_file }}"
        dest: "{{ dest_repo_file }}"
    
    - name: Install elastic
      shell: yum install -y elasticsearch

    - name: Copy config
      vars:
        cfg_file: elasticsearch-kibana.yml
      copy:
        src: "{{ cfg_file }}"
        dest: "{{ dest_cfg_file }}"
 
    - name: Copy config list hosts
      vars:
        cfg_file: unicast_hosts.txt
      copy:
        src: "{{ cfg_file }}"
        dest: "{{ dest_cfg_dir_elastic }}"

    - name: Start elastic
      service:
        name: elasticsearch
        state: started
        enabled: yes

